### ISSUE TITLE
请问如何更改ant的默认主题和样式，怎么加入css modules?

### ISSUE THREAD

**Issue by pookpal** [JasonBai007/reactSPA#1]
如题

**Comment by JasonBai007** [comment]
不好意思，这个还没研究，刚才看了看ant官网，没有发现不同的主题，好像只有一套主题，部分组件可以通过配置，改变颜色风格，比如导航。如果要改变样式，好像只能自己写样式覆盖原样式

**Comment by JasonBai007** [comment]
关键的一行是style-loader!css-loader?modules，它在css-loader后面加了一个查询参数modules，表示打开 CSS Modules 功能。
请参阅阮一峰的文章：http://www.ruanyifeng.com/blog/2016/06/css_modules.html

**Comment by pookpal** [comment]
恩，谢谢，解决了，antd提供了一个babel插件，我在你这个版本的基础上增加了自定义主题覆盖样式，css模块化，国际化，目前正在把redux融合进去

**Comment by cuijiaxu** [comment]
现在这一版的跳转有问题。antd那个页面的子组件都点不进去

**Comment by JasonBai007** [comment]
均已修复
