### ISSUE TITLE
npm start出错

### ISSUE THREAD

**Issue by jfyear1994** [JasonBai007/reactSPA#10]
![1](https://cloud.githubusercontent.com/assets/21995695/25610710/df3adb46-2f56-11e7-9651-3626db7ed071.png)

**Comment by sjf159026** [comment]
me too

**Comment by sjf159026** [comment]
"webpack": "1.13.2",
    "webpack-dev-server": "1.14.0"

加上这个就好了

**Comment by jfyear1994** [comment]
@sjf159026 
谢了，才发现json文件里是这样的
"webpack": "",
"webpack-dev-server": ""

**Comment by JasonBai007** [comment]
非常抱歉，版本管理这块儿我一直没有完善，前端各个包更新的太快，导致项目后期再安装包的时候，会出现问题，我近期抽时间改好
