### ISSUE TITLE
运行异常

### ISSUE THREAD

**Issue by hevine** [JasonBai007/reactSPA#3]
1.clone代码后，npm install 依赖包，npm run build,npm start, 
2.提示
main.bundle.js:88 Cannot find module './_defined'
 @ multi main

3.浏览器提示：
Uncaught Error: Cannot find module "C:\work\reactSPA\app\src\main.jsx"

**Comment by JasonBai007** [comment]
谢谢关注，最近我又提交了一些代码，做了很多改进和完善，可以再拉取一下试一试。
有任何问题可加我微信（1105843831）随时沟通。
