### ISSUE TITLE
background-image路径错误无法显示

### ISSUE THREAD

**Issue by cgd199158** [JasonBai007/reactSPA#6]
在学习您的demo时发现background-image背景图片路径错误无法显示,一直找不到问题所在,想请大神帮忙看一下是什么原因导致的,
GET http://localhost:8080/dist/css/distimg/last.jpg 404 (Not Found)
这是错误信息,这个路径是在哪里配置的?

**Comment by cgd199158** [comment]
在此先谢过了.demo非常棒

**Comment by cgd199158** [comment]
已解决,好像是output配置出了一些问题

**Comment by JasonBai007** [comment]
这个好像得在webpack中配置publicPath，刚看到，回复晚了。我要升级antd版本，以后几次提交，改动会非常大

**Comment by huangguangjie** [comment]
案例非常好。谢谢。但是在新版webpack2.0对就的很多插件都不能用了。要自己重新配置一下。

**Comment by JasonBai007** [comment]
谢谢，恩，webpack antd 一直在更新，这个项目是以前写的，不太兼容新版本了
