### ISSUE TITLE
安装依赖后运行报错

### ISSUE THREAD

**Issue by xunxichenzhilian** [JasonBai007/reactSPA#8]
![image](https://cloud.githubusercontent.com/assets/25715876/23738475/2a82c5ee-04d4-11e7-9ea3-48e63a05e849.png)
请问这是什么原因啊？

**Comment by banyaner** [comment]
### 一共有3个问题：
1. 是webpack.config.js 中的配置，报错中已经指出来了，需要改写成这样：
new webpack.optimize.CommonsChunkPlugin({name: 'vendors', filename: 'js/vendors.js'}),
2. package.json中没有写webpack等的版本号（1.x和2.x语法不太一样），默认就会下载最新版本。我把它写成了"webpack": "^1.13.2",不过 webpack-dev-server不知道应该是啥版本，可先不写。这时候执行npm run build
3. 启动服务命令应该是npm run start。不过还是会失败，因为缺了个文件。所以建议直接使用webpack-dev-server 开启热加载服务。

回复的可能有问题，望指正。
